package autonoma.oulgaslocas.ui;

import autonoma.pulgasLocas.elements.Battlefield;
import gamebase.elements.GraphicContainer;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;

/**
 *
 * @author Kamii
 */
public class GameWindow extends javax.swing.JFrame implements GraphicContainer{
    protected Battlefield battlefield;

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("Tecla presionada: " + evt.getKeyCode()); // Depuración
        if(evt.getKeyCode() == KeyEvent.VK_Q)
        {
            System.exit(0);
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_UP |
           evt.getKeyCode() == KeyEvent.VK_DOWN |
           evt.getKeyCode() == KeyEvent.VK_LEFT |
           evt.getKeyCode() == KeyEvent.VK_RIGHT)
        {
            battlefield.keyPressed(evt.getKeyCode());
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_SPACE)
        {
            battlefield.keyPressed(evt.getKeyCode());
        }

        if(evt.getKeyCode() == KeyEvent.VK_P)
        {
            battlefield.keyPressed(evt.getKeyCode());
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_M)
        {
            battlefield.keyPressed(evt.getKeyCode());
        }

        if(evt.getKeyCode() == KeyEvent.VK_S)
        {
            battlefield.keyPressed(evt.getKeyCode());
        }
    }//GEN-LAST:event_formKeyPressed
    public void setBattlefield(Battlefield battlefield) {
        this.battlefield = battlefield;
    }
    
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); 
    
        if(battlefield != null)
            battlefield.paint(g);
    }
    
    @Override
    public void refresh() {
        this.repaint();
    }

    @Override
    public Rectangle getBoundaries() {
        return this.getBounds();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
